import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

import { QueryProviders } from "@/providers/query-provider";
import AuthProvider from "@/providers/AuthProvider";

export const metadata: Metadata = {
  title: "SpendSmart",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-blue.svg",
  },
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="antialiased">
        <AuthProvider>
          <QueryProviders>{children}</QueryProviders>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
